### ISSUE TITLE
Не работает на reddit

### ISSUE THREAD

**Issue by ghost** [memfinis/Landing#1]
Не переводит текст на reddit.com

P.S. рассмотрите возможность вместо зажатия горячей клавиши одновременно и выделения текста переводить выделенный текст просто по сочетанию клавиш например alt+t, аналогично расширению переводчика от google, во всем остальном - 10 баллов.

**Comment by vostlertsd** [comment]
В 5.0.3 перевод на reddit.com исправлен + добавлена комбинация alt+t для перевода выделенного текста на страницах.

P.S. 5.0.3 - ожидает модерации в сторе

**Comment by ghost** [comment]
Всё работает идеально! Спасибо за столь оперативный апдейт!
